### ISSUE TITLE
Vigenere Cipher

### ISSUE THREAD

**Issue by Dasc3er** [karan/Projects#91]
I believe it would be great to add the _Vigenere Cipher_ in the **Security** section...
What do you think?

**Comment by Himanshu1495** [comment]
@Dasc3er, can I try implementing vigenere cipher in Python?

**Comment by Dasc3er** [comment]
@Himanshu1495 You can do it quite simply :)
If you want to see my version, check this repository: https://github.com/Dasc3er/Contributions
